version: "3.5"
services:
  zinc:
    image: hiprabhat/zinc:0.1.3
    ports:
      - "4082:4082"
    environment:
      - DATA_PATH=/data
      - FIRST_ADMIN_USER=admin
      - FIRST_ADMIN_PASSWORD=admin123
    volumes:
      - ./data:/data
